In [1]:
import numpy as np
import pandas as pd

### Different ways of creating Pandas Series
1. From a list
2. From a Numpy Array
3. From a Dictionary

In [4]:
import pandas as pd

# From a list
data = [10, 20, 30, 40, 50]
s1 = pd.Series(data)
print(s1)
# From a NumPy array
import numpy as np
data_array = np.array([10, 20, 30, 40, 50])
s2 = pd.Series(data_array)
print(s2)

0    10
1    20
2    30
3    40
4    50
dtype: int64
0    10
1    20
2    30
3    40
4    50
dtype: int32

In [6]:
#From a dict
data_dict = {'A': 10, 'B': 20, 'C': 30, 'D': 40, 'E': 50}
s_dict = pd.Series(data_dict)
print(s_dict)

A    10
B    20
C    30
D    40
E    50
dtype: int64

## 2. Operations on Pandas Series 
1. Indexing and Slicing
2. Mean and Max functions
3. Sorting
4. Unique values

In [9]:
import pandas as pd

# Creating a Pandas Series
data = {'A': 10, 'B': 20, 'C': 30, 'D': 40, 'E': 50}
s = pd.Series(data)

# Indexing and Slicing
print("Element at index 'B':", s['B'])
print("Elements from index 'B' to 'D':")
print(s['B':'D'])

# Descriptive Statistics
print("\nMean:", s.mean())
print("Max:", s.max())

# Boolean Operations
print("\nElements greater than 25:")
print(s[s > 25])

# Sorting
print("\nSorted by index:")
print(s.sort_index())
print("\nSorted by values:")
print(s.sort_values(ascending=False))

# Unique Values and Value Counts
print("\nUnique values:")
print(s.unique())
print("\nValue counts:")
print(s.value_counts())

Element at index 'B': 20
Elements from index 'B' to 'D':
B    20
C    30
D    40
dtype: int64

Mean: 30.0
Max: 50

Elements greater than 25:
C    30
D    40
E    50
dtype: int64

Sorted by index:
A    10
B    20
C    30
D    40
E    50
dtype: int64

Sorted by values:
E    50
D    40
C    30
B    20
A    10
dtype: int64

Unique values:
[10 20 30 40 50]

Value counts:
10    1
20    1
30    1
40    1
50    1
Name: count, dtype: int64

## Dataframe
Data frames can be created from
1. A list
2. A dictionary
3. A csv file

In [12]:
#1. Dataframes created from a list

# Creating a list of lists
data = [[1, 'John', 25],
        [2, 'Alice', 30],
        [3, 'Bob', 35]]

# Creating a DataFrame from the list
df = pd.DataFrame(data, columns=['ID', 'Name', 'Age'])

print(df)

   ID   Name  Age
0   1   John   25
1   2  Alice   30
2   3    Bob   35

In [14]:
#Data frame created from a dictionary

data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'City': ['New York', 'Los Angeles', 'Chicago']}

df_dict = pd.DataFrame(data)
print(df_dict)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [29]:
df = pd.read_csv('Telco-Churn.csv')
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

### Working with Dataframe operations

In [19]:
#head by default displays the first 5 rows
print(df.head())
#tail by default display the last 5 rows
print(df.tail())
#describe describes the dataset
print(df.describe())

   ID   Name  Age
0   1   John   25
1   2  Alice   30
2   3    Bob   35
   ID   Name  Age
0   1   John   25
1   2  Alice   30
2   3    Bob   35
        ID   Age
count  3.0   3.0
mean   2.0  30.0
std    1.0   5.0
min    1.0  25.0
25%    1.5  27.5
50%    2.0  30.0
75%    2.5  32.5
max    3.0  35.0

In [21]:
#shape function displays the rows and columns in the dataset
print("\n The shape of the dataset:")
df.shape

 The shape of the dataset:

(3, 3)

In [23]:
#columns function displays the columns in the dataset
print("\nThe column headings of the dataset:")
df.columns

The column headings of the dataset:

Index(['ID', 'Name', 'Age'], dtype='object')

In [25]:
#printing values
print("\n The values of the dataset:")
df.values

 The values of the dataset:

array([[1, 'John', 25],
       [2, 'Alice', 30],
       [3, 'Bob', 35]], dtype=object)

In [31]:
#dropping specific columns
print("\nDrop 'Gender' column:")
print(df.drop(columns=['gender']))

Drop 'Gender' column:
      customerID  SeniorCitizen Partner Dependents  tenure PhoneService  \
0     7590-VHVEG              0     Yes         No       1           No
1     5575-GNVDE              0      No         No      34          Yes
2     3668-QPYBK              0      No         No       2          Yes
3     7795-CFOCW              0      No         No      45           No
4     9237-HQITU              0      No         No       2          Yes
...          ...            ...     ...        ...     ...          ...
7038  6840-RESVB              0     Yes        Yes      24          Yes
7039  2234-XADUH              0     Yes        Yes      72          Yes
7040  4801-JZAZL              0     Yes        Yes      11           No
7041  8361-LTMKD              1     Yes         No       4          Yes
7042  3186-AJIEK              0      No         No      66          Yes

         MultipleLines InternetService OnlineSecurity OnlineBackup  \
0     No phone service             DSL             No          Yes
1                   No             DSL            Yes           No
2                   No             DSL            Yes          Yes
3     No phone service             DSL            Yes           No
4                   No     Fiber optic             No           No
...                ...             ...            ...          ...
7038               Yes             DSL            Yes           No
7039               Yes     Fiber optic             No          Yes
7040  No phone service             DSL            Yes           No
7041               Yes     Fiber optic             No           No
7042                No     Fiber optic            Yes           No

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month
1                 Yes          No          No              No        One year
2                  No          No          No              No  Month-to-month
3                 Yes         Yes          No              No        One year
4                  No          No          No              No  Month-to-month
...               ...         ...         ...             ...             ...
7038              Yes         Yes         Yes             Yes        One year
7039              Yes          No         Yes             Yes        One year
7040               No          No          No              No  Month-to-month
7041               No          No          No              No  Month-to-month
7042              Yes         Yes         Yes             Yes        Two year

     PaperlessBilling              PaymentMethod  MonthlyCharges TotalCharges  \
0                 Yes           Electronic check           29.85        29.85
1                  No               Mailed check           56.95       1889.5
2                 Yes               Mailed check           53.85       108.15
3                  No  Bank transfer (automatic)           42.30      1840.75
4                 Yes           Electronic check           70.70       151.65
...               ...                        ...             ...          ...
7038              Yes               Mailed check           84.80       1990.5
7039              Yes    Credit card (automatic)          103.20       7362.9
7040              Yes           Electronic check           29.60       346.45
7041              Yes               Mailed check           74.40        306.6
7042              Yes  Bank transfer (automatic)          105.65       6844.5

     Churn
0       No
1       No
2      Yes
3       No
4      Yes
...    ...
7038    No
7039    No
7040    No
7041   Yes
7042    No

[7043 rows x 20 columns]

In [33]:
#removing duplicate values
print("\nDrop duplicates:")
print(df.drop_duplicates())

Drop duplicates:
      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1
1     5575-GNVDE    Male              0      No         No      34
2     3668-QPYBK    Male              0      No         No       2
3     7795-CFOCW    Male              0      No         No      45
4     9237-HQITU  Female              0      No         No       2
...          ...     ...            ...     ...        ...     ...
7038  6840-RESVB    Male              0     Yes        Yes      24
7039  2234-XADUH  Female              0     Yes        Yes      72
7040  4801-JZAZL  Female              0     Yes        Yes      11
7041  8361-LTMKD    Male              1     Yes         No       4
7042  3186-AJIEK    Male              0      No         No      66

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...
1             Yes                No             DSL            Yes  ...
2             Yes                No             DSL            Yes  ...
3              No  No phone service             DSL            Yes  ...
4             Yes                No     Fiber optic             No  ...
...           ...               ...             ...            ...  ...
7038          Yes               Yes             DSL            Yes  ...
7039          Yes               Yes     Fiber optic             No  ...
7040           No  No phone service             DSL            Yes  ...
7041          Yes               Yes     Fiber optic             No  ...
7042          Yes                No     Fiber optic            Yes  ...

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month
1                 Yes          No          No              No        One year
2                  No          No          No              No  Month-to-month
3                 Yes         Yes          No              No        One year
4                  No          No          No              No  Month-to-month
...               ...         ...         ...             ...             ...
7038              Yes         Yes         Yes             Yes        One year
7039              Yes          No         Yes             Yes        One year
7040               No          No          No              No  Month-to-month
7041               No          No          No              No  Month-to-month
7042              Yes         Yes         Yes             Yes        Two year

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0                 Yes           Electronic check          29.85         29.85
1                  No               Mailed check          56.95        1889.5
2                 Yes               Mailed check          53.85        108.15
3                  No  Bank transfer (automatic)          42.30       1840.75
4                 Yes           Electronic check          70.70        151.65
...               ...                        ...            ...           ...
7038              Yes               Mailed check          84.80        1990.5
7039              Yes    Credit card (automatic)         103.20        7362.9
7040              Yes           Electronic check          29.60        346.45
7041              Yes               Mailed check          74.40         306.6
7042              Yes  Bank transfer (automatic)         105.65        6844.5

     Churn
0       No
1       No
2      Yes
3       No
4      Yes
...    ...
7038    No
7039    No
7040    No
7041   Yes
7042    No

[7043 rows x 21 columns]

In [35]:
#Checking  null values
# fillna()
print("\nFill missing values with 0:")
print(df.fillna(0))

Fill missing values with 0:
      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1
1     5575-GNVDE    Male              0      No         No      34
2     3668-QPYBK    Male              0      No         No       2
3     7795-CFOCW    Male              0      No         No      45
4     9237-HQITU  Female              0      No         No       2
...          ...     ...            ...     ...        ...     ...
7038  6840-RESVB    Male              0     Yes        Yes      24
7039  2234-XADUH  Female              0     Yes        Yes      72
7040  4801-JZAZL  Female              0     Yes        Yes      11
7041  8361-LTMKD    Male              1     Yes         No       4
7042  3186-AJIEK    Male              0      No         No      66

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...
1             Yes                No             DSL            Yes  ...
2             Yes                No             DSL            Yes  ...
3              No  No phone service             DSL            Yes  ...
4             Yes                No     Fiber optic             No  ...
...           ...               ...             ...            ...  ...
7038          Yes               Yes             DSL            Yes  ...
7039          Yes               Yes     Fiber optic             No  ...
7040           No  No phone service             DSL            Yes  ...
7041          Yes               Yes     Fiber optic             No  ...
7042          Yes                No     Fiber optic            Yes  ...

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month
1                 Yes          No          No              No        One year
2                  No          No          No              No  Month-to-month
3                 Yes         Yes          No              No        One year
4                  No          No          No              No  Month-to-month
...               ...         ...         ...             ...             ...
7038              Yes         Yes         Yes             Yes        One year
7039              Yes          No         Yes             Yes        One year
7040               No          No          No              No  Month-to-month
7041               No          No          No              No  Month-to-month
7042              Yes         Yes         Yes             Yes        Two year

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0                 Yes           Electronic check          29.85         29.85
1                  No               Mailed check          56.95        1889.5
2                 Yes               Mailed check          53.85        108.15
3                  No  Bank transfer (automatic)          42.30       1840.75
4                 Yes           Electronic check          70.70        151.65
...               ...                        ...            ...           ...
7038              Yes               Mailed check          84.80        1990.5
7039              Yes    Credit card (automatic)         103.20        7362.9
7040              Yes           Electronic check          29.60        346.45
7041              Yes               Mailed check          74.40         306.6
7042              Yes  Bank transfer (automatic)         105.65        6844.5

     Churn
0       No
1       No
2      Yes
3       No
4      Yes
...    ...
7038    No
7039    No
7040    No
7041   Yes
7042    No

[7043 rows x 21 columns]

In [37]:
# Checking for missing values and non-missing values
print("\nCheck for missing values:")
print(df.isnull())
print("\nCheck for non-missing values:")
print(df.notnull())

Check for missing values:
      customerID  gender  SeniorCitizen  Partner  Dependents  tenure  \
0          False   False          False    False       False   False
1          False   False          False    False       False   False
2          False   False          False    False       False   False
3          False   False          False    False       False   False
4          False   False          False    False       False   False
...          ...     ...            ...      ...         ...     ...
7038       False   False          False    False       False   False
7039       False   False          False    False       False   False
7040       False   False          False    False       False   False
7041       False   False          False    False       False   False
7042       False   False          False    False       False   False

      PhoneService  MultipleLines  InternetService  OnlineSecurity  ...  \
0            False          False            False           False  ...
1            False          False            False           False  ...
2            False          False            False           False  ...
3            False          False            False           False  ...
4            False          False            False           False  ...
...            ...            ...              ...             ...  ...
7038         False          False            False           False  ...
7039         False          False            False           False  ...
7040         False          False            False           False  ...
7041         False          False            False           False  ...
7042         False          False            False           False  ...

      DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0                False        False        False            False     False
1                False        False        False            False     False
2                False        False        False            False     False
3                False        False        False            False     False
4                False        False        False            False     False
...                ...          ...          ...              ...       ...
7038             False        False        False            False     False
7039             False        False        False            False     False
7040             False        False        False            False     False
7041             False        False        False            False     False
7042             False        False        False            False     False

      PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  Churn
0                False          False           False         False  False
1                False          False           False         False  False
2                False          False           False         False  False
3                False          False           False         False  False
4                False          False           False         False  False
...                ...            ...             ...           ...    ...
7038             False          False           False         False  False
7039             False          False           False         False  False
7040             False          False           False         False  False
7041             False          False           False         False  False
7042             False          False           False         False  False

[7043 rows x 21 columns]

Check for non-missing values:
      customerID  gender  SeniorCitizen  Partner  Dependents  tenure  \
0           True    True           True     True        True    True
1           True    True           True     True        True    True
2           True    True           True     True        True    True
3           True    True           True     True        True    True
4           True    True           True     True        True    True
...          ...     ...            ...      ...         ...     ...
7038        True    True           True     True        True    True
7039        True    True           True     True        True    True
7040        True    True           True     True        True    True
7041        True    True           True     True        True    True
7042        True    True           True     True        True    True

      PhoneService  MultipleLines  InternetService  OnlineSecurity  ...  \
0             True           True             True            True  ...
1             True           True             True            True  ...
2             True           True             True            True  ...
3             True           True             True            True  ...
4             True           True             True            True  ...
...            ...            ...              ...             ...  ...
7038          True           True             True            True  ...
7039          True           True             True            True  ...
7040          True           True             True            True  ...
7041          True           True             True            True  ...
7042          True           True             True            True  ...

      DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0                 True         True         True             True      True
1                 True         True         True             True      True
2                 True         True         True             True      True
3                 True         True         True             True      True
4                 True         True         True             True      True
...                ...          ...          ...              ...       ...
7038              True         True         True             True      True
7039              True         True         True             True      True
7040              True         True         True             True      True
7041              True         True         True             True      True
7042              True         True         True             True      True

      PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  Churn
0                 True           True            True          True   True
1                 True           True            True          True   True
2                 True           True            True          True   True
3                 True           True            True          True   True
4                 True           True            True          True   True
...                ...            ...             ...           ...    ...
7038              True           True            True          True   True
7039              True           True            True          True   True
7040              True           True            True          True   True
7041              True           True            True          True   True
7042              True           True            True          True   True

[7043 rows x 21 columns]

In [39]:
#Getting summary statistics of a specific column
# mean() / median() / sum() / min() / max()
print("\nSummary statistics of tenure:")
print("Mean :", df['tenure'].mean())
print("Median :", df['tenure'].median())
print("Total :", df['tenure'].sum())
print("Minimum :", df['tenure'].min())
print("Maximum :", df['tenure'].max())

Summary statistics of tenure:
Mean : 32.37114865824223
Median : 29.0
Total : 227990
Minimum : 0
Maximum : 72

## DataFrame Indexing operations

In [42]:
# Selecting Columns
print("Selecting Columns:")
print(df['customerID'])  # Using square brackets
print(df.tenure)      # Using dot notation

Selecting Columns:
0       7590-VHVEG
1       5575-GNVDE
2       3668-QPYBK
3       7795-CFOCW
4       9237-HQITU
           ...
7038    6840-RESVB
7039    2234-XADUH
7040    4801-JZAZL
7041    8361-LTMKD
7042    3186-AJIEK
Name: customerID, Length: 7043, dtype: object
0        1
1       34
2        2
3       45
4        2
        ..
7038    24
7039    72
7040    11
7041     4
7042    66
Name: tenure, Length: 7043, dtype: int64

In [44]:
# Selecting Rows
print("\nSelecting Rows:")
print("Using .loc[]:")
print(df.loc[1])   # Label-based indexing
print("Using .iloc[]:")
print(df.iloc[2])  # Integer-based indexing
print("Using boolean indexing:")
print(df[df['tenure'] > 30])  # Boolean indexing

Selecting Rows:
Using .loc[]:
customerID            5575-GNVDE
gender                      Male
SeniorCitizen                  0
Partner                       No
Dependents                    No
tenure                        34
PhoneService                 Yes
MultipleLines                 No
InternetService              DSL
OnlineSecurity               Yes
OnlineBackup                  No
DeviceProtection             Yes
TechSupport                   No
StreamingTV                   No
StreamingMovies               No
Contract                One year
PaperlessBilling              No
PaymentMethod       Mailed check
MonthlyCharges             56.95
TotalCharges              1889.5
Churn                         No
Name: 1, dtype: object
Using .iloc[]:
customerID              3668-QPYBK
gender                        Male
SeniorCitizen                    0
Partner                         No
Dependents                      No
tenure                           2
PhoneService                   Yes
MultipleLines                   No
InternetService                DSL
OnlineSecurity                 Yes
OnlineBackup                   Yes
DeviceProtection                No
TechSupport                     No
StreamingTV                     No
StreamingMovies                 No
Contract            Month-to-month
PaperlessBilling               Yes
PaymentMethod         Mailed check
MonthlyCharges               53.85
TotalCharges                108.15
Churn                          Yes
Name: 2, dtype: object
Using boolean indexing:
      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
1     5575-GNVDE    Male              0      No         No      34
3     7795-CFOCW    Male              0      No         No      45
9     6388-TABGU    Male              0      No        Yes      62
12    8091-TTVAX    Male              0     Yes         No      58
13    0280-XJGEX    Male              0      No         No      49
...          ...     ...            ...     ...        ...     ...
7033  9767-FFLEM    Male              0      No         No      38
7034  0639-TSIQW  Female              0      No         No      67
7037  2569-WGERO  Female              0      No         No      72
7039  2234-XADUH  Female              0     Yes        Yes      72
7042  3186-AJIEK    Male              0      No         No      66

     PhoneService     MultipleLines InternetService       OnlineSecurity  ...  \
1             Yes                No             DSL                  Yes  ...
3              No  No phone service             DSL                  Yes  ...
9             Yes                No             DSL                  Yes  ...
12            Yes               Yes     Fiber optic                   No  ...
13            Yes               Yes     Fiber optic                   No  ...
...           ...               ...             ...                  ...  ...
7033          Yes                No     Fiber optic                   No  ...
7034          Yes               Yes     Fiber optic                  Yes  ...
7037          Yes                No              No  No internet service  ...
7039          Yes               Yes     Fiber optic                   No  ...
7042          Yes                No     Fiber optic                  Yes  ...

         DeviceProtection          TechSupport          StreamingTV  \
1                     Yes                   No                   No
3                     Yes                  Yes                   No
9                      No                   No                   No
12                    Yes                   No                  Yes
13                    Yes                   No                  Yes
...                   ...                  ...                  ...
7033                   No                   No                   No
7034                  Yes                   No                  Yes
7037  No internet service  No internet service  No internet service
7039                  Yes                   No                  Yes
7042                  Yes                  Yes                  Yes

          StreamingMovies        Contract PaperlessBilling  \
1                      No        One year               No
3                      No        One year               No
9                      No        One year               No
12                    Yes        One year               No
13                    Yes  Month-to-month              Yes
...                   ...             ...              ...
7033                   No  Month-to-month              Yes
7034                   No  Month-to-month              Yes
7037  No internet service        Two year              Yes
7039                  Yes        One year              Yes
7042                  Yes        Two year              Yes

                  PaymentMethod MonthlyCharges  TotalCharges Churn
1                  Mailed check          56.95        1889.5    No
3     Bank transfer (automatic)          42.30       1840.75    No
9     Bank transfer (automatic)          56.15       3487.95    No
12      Credit card (automatic)         100.35        5681.1    No
13    Bank transfer (automatic)         103.70        5036.3   Yes
...                         ...            ...           ...   ...
7033    Credit card (automatic)          69.50       2625.25    No
7034    Credit card (automatic)         102.95       6886.25   Yes
7037  Bank transfer (automatic)          21.15        1419.4    No
7039    Credit card (automatic)         103.20        7362.9    No
7042  Bank transfer (automatic)         105.65        6844.5    No

[3402 rows x 21 columns]

In [46]:
# Selecting Rows and Columns
print("\nSelecting Rows and Columns:")
print(df.loc[1, 'customerID'])   # Label-based indexing
print(df.iloc[2, 1])       # Integer-based indexing
print(df[df['tenure'] > 30]['customerID'])  # Boolean indexing for rows and selecting column

Selecting Rows and Columns:
5575-GNVDE
Male
1       5575-GNVDE
3       7795-CFOCW
9       6388-TABGU
12      8091-TTVAX
13      0280-XJGEX
           ...
7033    9767-FFLEM
7034    0639-TSIQW
7037    2569-WGERO
7039    2234-XADUH
7042    3186-AJIEK
Name: customerID, Length: 3402, dtype: object

In [48]:
# Conditional Selection
print("\nConditional Selection:")
print(df[df['gender'] == 'Male'])  # Selecting rows based on a condition

Conditional Selection:
      customerID gender  SeniorCitizen Partner Dependents  tenure  \
1     5575-GNVDE   Male              0      No         No      34
2     3668-QPYBK   Male              0      No         No       2
3     7795-CFOCW   Male              0      No         No      45
6     1452-KIOVK   Male              0      No        Yes      22
9     6388-TABGU   Male              0      No        Yes      62
...          ...    ...            ...     ...        ...     ...
7033  9767-FFLEM   Male              0      No         No      38
7035  8456-QDAVC   Male              0      No         No      19
7038  6840-RESVB   Male              0     Yes        Yes      24
7041  8361-LTMKD   Male              1     Yes         No       4
7042  3186-AJIEK   Male              0      No         No      66

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
1             Yes                No             DSL            Yes  ...
2             Yes                No             DSL            Yes  ...
3              No  No phone service             DSL            Yes  ...
6             Yes               Yes     Fiber optic             No  ...
9             Yes                No             DSL            Yes  ...
...           ...               ...             ...            ...  ...
7033          Yes                No     Fiber optic             No  ...
7035          Yes                No     Fiber optic             No  ...
7038          Yes               Yes             DSL            Yes  ...
7041          Yes               Yes     Fiber optic             No  ...
7042          Yes                No     Fiber optic            Yes  ...

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
1                 Yes          No          No              No        One year
2                  No          No          No              No  Month-to-month
3                 Yes         Yes          No              No        One year
6                  No          No         Yes              No  Month-to-month
9                  No          No          No              No        One year
...               ...         ...         ...             ...             ...
7033               No          No          No              No  Month-to-month
7035               No          No         Yes              No  Month-to-month
7038              Yes         Yes         Yes             Yes        One year
7041               No          No          No              No  Month-to-month
7042              Yes         Yes         Yes             Yes        Two year

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
1                  No               Mailed check          56.95        1889.5
2                 Yes               Mailed check          53.85        108.15
3                  No  Bank transfer (automatic)          42.30       1840.75
6                 Yes    Credit card (automatic)          89.10        1949.4
9                  No  Bank transfer (automatic)          56.15       3487.95
...               ...                        ...            ...           ...
7033              Yes    Credit card (automatic)          69.50       2625.25
7035              Yes  Bank transfer (automatic)          78.70        1495.1
7038              Yes               Mailed check          84.80        1990.5
7041              Yes               Mailed check          74.40         306.6
7042              Yes  Bank transfer (automatic)         105.65        6844.5

     Churn
1       No
2      Yes
3       No
6       No
9       No
...    ...
7033    No
7035    No
7038    No
7041   Yes
7042    No

[3555 rows x 21 columns]

In [ ]:
# Setting Index
print("\nSetting Index:")
df_indexed = df.set_index('customerID')
print(df_indexed)

In [ ]:
# Sorting by a single column
sorted_df = df.sort_values(by='tenure')
print("\nSorted DataFrame:")
print(sorted_df)